name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Check out code

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1

    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: open-webui
        platform: linux/arm64
        enableBuildKit: true
        tags: v1
        registry: 593537320251.dkr.ecr.ap-south-1.amazonaws.com
        dockerfile: Dockerfile
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.LUNA_AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.LUNA_AWS_SECRET_ACCESS_KEY }}
